job:
  image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
  namespace: inteldeviceplugin

serviceAccountName: mcp-qat-config-sa
rbac:
  roles:
    - name: qat-config-role
      createRole: true
      apiGroups:
        - '"apiextensions.k8s.io"'
        - '"machineconfiguration.openshift.io"'
        - '"deviceplugin.intel.com"'
      scope:
        cluster: true
      resources:
        - machineconfigs
      verbs:
        - "get"
        - "list"
        - "patch"
        - "update"
        - "create"
  roleBindings:
    - name: qat-config-rolebinding
      createBinding: true
      scope:
        cluster: true
        namespace: ""
      subjects:
        kind: ServiceAccount
        name: mcp-qat-config-sa
        namespace: inteldeviceplugin
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: qat-config-role