---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: tei-gaudi
  namespace: {{ .Values.global.gaudillm.namespace }}
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: chatqna
  namespace: {{ .Values.global.gaudillm.namespace }}
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: chatqna-ui
  namespace: {{ .Values.global.gaudillm.namespace }}
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: llm-tgi
  namespace: {{ .Values.global.gaudillm.namespace }}
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: reranking-tei
  namespace: {{ .Values.global.gaudillm.namespace }}
spec:
  lookupPolicy:
    local: true
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: retriever-redis
  namespace: {{ .Values.global.gaudillm.namespace }}
spec:
  lookupPolicy:
    local: true
