apiVersion: v1
kind: ConfigMap
metadata:
  name: patch-kserve-progress-deadline
  namespace: {{ .Values.global.gaudillm.namespace }}
data:
  patch-kserve-progress-deadline.sh: |
    #!/bin/bash
    echo "Patching knative-serving config to include 30m progressDeadline for model servings..."
    oc patch -n knative-serving knativeserving knative-serving --patch '{"spec":{"config":{"deployment":{"progress-deadline":"30m"}}}}'
