apiVersion: dashboard.opendatahub.io/v1
kind: AcceleratorProfile
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  name: zzgaudi-2
  namespace: redhat-ods-applications
spec:
  displayName: Gaudi 2
  enabled: true
  identifier: habana.ai/gaudi
  tolerations: []
