global: 
  pattern: gaudillm

  gaudillm:
    namespace: gaudi-llm
    build_envs: [] # http_proxy/https_prxy can be set here
    runtime_envs: []

    tei_embedding:
      image: image-registry.openshift-image-registry.svc:5000/gaudi-llm/gen-ai-comps:tei-gaudi
      pvc:
        size: 3Gi
      model_id: BAAI/bge-large-en-v1.5
