apiVersion: v1
kind: ConfigMap
metadata:
  name: wait-for-istio-operator
  namespace: openshift-operators
  annotations:
    argocd.argoproj.io/sync-wave: "-210"
data:
  wait-for-istio-operator.sh: |
    #!/bin/bash

    waiting_time=10
    
    until [[ $(oc get ip -n openshift-operators) == *"sailoperator"*  ]]
    do
      sleep ${waiting_time}
    done
    sleep ${waiting_time}
