apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-200"
  name: job-approve-istio-operator
  namespace: openshift-operators
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
           '/tmp/wait-for-istio-operator.sh' && \
           oc patch installplan $(oc get ip -n openshift-operators -o=jsonpath='{.items[?(@.spec.approved==false)].metadata.name}') -n openshift-operators --type merge --patch '{"spec":{"approved":true}}'
        name: wait-for-istio-operator
        volumeMounts:
          - mountPath: /tmp/wait-for-istio-operator.sh
            name: wait-for-istio-operator
            subPath: wait-for-istio-operator.sh
      volumes:
        - name: wait-for-istio-operator
          configMap:
            name: wait-for-istio-operator
            defaultMode: 0755
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: {{ .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      terminationGracePeriodSeconds: 60