apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker_compose.yaml
    kompose.version: 1.33.0 (3ce457399)
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-wave: "5"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"chatqna:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"chatqna-gaudi-backend-server\")].image"}]'
  labels:
    io.kompose.service: chatqna-gaudi-backend-server
  name: chatqna-gaudi-backend-server
  namespace: {{ .Values.global.gaudillm.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: chatqna-gaudi-backend-server
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker_compose.yaml
        kompose.version: 1.33.0 (3ce457399)
      labels:
        io.kompose.network/gaudi-default: "true"
        io.kompose.service: chatqna-gaudi-backend-server
    spec:
      containers:
        - command:
          - /bin/bash
          - -c
          - |
            cp chatqna.py /tmp/chatqna.py && \
            sed -i "s/6000/80/" /tmp/chatqna.py && \
            sed -i "s/7000/80/" /tmp/chatqna.py && \
            sed -i "s/8000/80/" /tmp/chatqna.py && \
            sed -i "s/9000/80/" /tmp/chatqna.py && \
            ls /tmp && \
            python /tmp/chatqna.py
          env:
            - name: MEGA_SERVICE_HOST_IP
              value: megaservice-{{ .Values.global.gaudillm.namespace }}.apps.{{ .Values.global.clusterDomain }}
            {{- if .Values.global.gaudillm.runtime_envs }}
            {{- range .Values.global.gaudillm.runtime_envs }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
            {{- end }}
          image: {{ .Values.global.gaudillm.chatqna_gaudi_backend.image }}
          name: chatqna-gaudi-backend-server
          ports:
            - containerPort: 8888
              protocol: TCP
      restartPolicy: Always
