apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-1"
  name: job-wait-for-istio
  namespace: {{ .Values.workload.namespace }}
spec:
  template:
    metadata:
      labels:
        sidecar.istio.io/inject: 'false'
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
           '/tmp/wait-for-istio.sh'
        name: wait-for-istio
        volumeMounts:
          - mountPath: /tmp/wait-for-istio.sh
            name: wait-for-istio
            subPath: wait-for-istio.sh
      volumes:
        - name: wait-for-istio
          configMap:
            name: wait-for-istio
            defaultMode: 0755
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: {{ .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      terminationGracePeriodSeconds: 60