---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: httpbin-credential
  namespace: istio-system
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: httpbin-credential
    template:
      type: Opaque
  data:
  - secretKey: ca.crt
    remoteRef:
      key: {{ .Values.applicationsecret.key }}
      property: examplecert
  - secretKey: tls.crt
    remoteRef:
      key: {{ .Values.applicationsecret.key }}
      property: httpbincert
  - secretKey: tls.key
    remoteRef:
      key: {{ .Values.applicationsecret.key }}
      property: httpbinkey