---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: httpbin-credential
  namespace: {{ .Values.workload.namespace }}
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: httpbin-credential
    template:
      type: Opaque
  data:
  - secretKey: ca.crt
    remoteRef:
      key: {{ .Values.applicationsecret.key }}/examplecert
      property: content
  - secretKey: tls.crt
    remoteRef:
      key: {{ .Values.applicationsecret.key }}/httpbincert
      property: content
  - secretKey: tls.key
    remoteRef:
      key: {{ .Values.applicationsecret.key }}/httpbinkey
      property: content