apiVersion: operator.istio.io/v1alpha1
kind: Istio
metadata:
  name: istio-system
spec:
  values:
    meshConfig:
      defaultConfig:
        privateKeyProvider:
          qat:
            pollDelay: 5ms
    sidecarInjectorWebhook:
      templates:
        custom: |
          spec:
            containers:
            - name: istio-proxy
              securityContext:
                privileged: true
                allowPrivilegeEscalation: true
  updateStrategy:
    inactiveRevisionDeletionGracePeriodSeconds: 30
    type: InPlace
  namespace: istio-system
  version: v1.20.1
