apiVersion: operator.istio.io/v1alpha1
kind: Istio
metadata:
  name: istio-system
spec:
  values:
    meshConfig:
      defaultConfig:
        privateKeyProvider:
          qat:
            pollDelay: 5ms
    global:
      proxy:
        privileged: true
  updateStrategy:
    inactiveRevisionDeletionGracePeriodSeconds: 30
    type: InPlace
  namespace: istio-system
  version: v1.20.1
