apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  name: job-enable-sidecar-injection
  namespace: {{ .Values.workload.namespace }}
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          oc label namespace {{ .Values.workload.namespace }} istio-injection=enabled --overwrite
          oc -n {{ .Values.workload.namespace }} annotate deploy {{ .Values.workload.name }} inject.istio.io/templates='sidecar,custom'
        name: inject-sidecar-proxy
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: {{ .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      terminationGracePeriodSeconds: 400
