apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  name: job-enable-sidecar-injection
  namespace: istio-system
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        command:
        - /bin/bash
        - -c
        - |
          oc adm policy add-scc-to-user nonroot-v2-istio -z default -n istio-system
          oc label namespace {{ .Values.workload.namespace }} istio.io/rev=istio-system --overwrite
          oc label namespace istio-system istio.io/rev=istio-system --overwrite
        name: inject-sidecar-proxy
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccount: {{ .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      terminationGracePeriodSeconds: 400
