apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: minio-secret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: minio-secret
    template:
      type: Opaque
  data:
  - secretKey: minio-root-user
    remoteRef:
      key: {{ .Values.applicationsecret.key }}/examplecert
      property: content
  - secretKey: minio-root-password
    remoteRef:
      key: {{ .Values.applicationsecret.key }}/httpbincert
      property: content