apiVersion: machineconfiguration.openshift.io/v1
kind: KubeletConfig
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-101"
  name: set-pid-limit-kubelet
spec:
  machineConfigPoolSelector:
    matchLabels:
      custom-kubelet: set-pod-pid-limit-kubelet
  kubeletConfig:
    podPidsLimit: {{ .Values.kubeletconfig.podPidsLimit }}