global: 
  pattern: gaudillm

  gaudillm:
    namespace: gaudi-llm
    build_envs: [] # http_proxy/https_prxy can be set here 
    runtime_envs: []
    
    retriever:
      image: image-registry.openshift-image-registry.svc:5000/gaudi-llm/gen-ai-comps:retriever-redis-server 
      git_ref: ecb8c79 # make sure to validate buildconfig & other change scope before updating
