workload:
  namespace: httpbin
  name: httpbin

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

applicationsecret:
  key: secret/global

job:
  image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest

machineconfigName:
  iommu: 100-intel-qat-intel-iommu-on
  fwpath: 100-alternative-fw-path-for-worker-nodes

serviceAccountName: istio-sidecar-injection-sa
rbac:
  roles:
    - name: sidecar-injection
      createRole: true
      apiGroups:
        - '""'
        - '"apps"'
        - '"machineconfiguration.openshift.io"'
      scope:
        cluster: true
      resources:
        - namespaces
        - deployments
        - machineconfigpools
      verbs:
        - "get"
        - "list"
        - "patch"
        - "update"
  roleBindings:
    - name: sidecar-injection
      createBinding: true
      scope:
        cluster: true
        namespace: ""
      subjects:
        kind: ServiceAccount
        name: istio-sidecar-injection-sa
        namespace: istio-system
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: sidecar-injection