workload:
  namespace: istio-system
  name: httpbin

secretStore:
  name: vault-backend
  kind: ClusterSecretStore

applicationsecret:
  key: secret/global

job:
  image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest

serviceAccountName: istio-sidecar-injection-sa
rbac:
  roles:
    - name: sidecar-injection
      createRole: true
      apiGroups:
        - '""'
        - '"apps"'
      scope:
        cluster: true
      resources:
        - namespaces
        - deployments
      verbs:
        - "get"
        - "list"
        - "patch"
        - "update"
  roleBindings:
    - name: sidecar-injection
      createBinding: true
      scope:
        cluster: true
        namespace: ""
      subjects:
        kind: ServiceAccount
        name: istio-sidecar-injection-sa
        namespace: istio-system
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: sidecar-injection