apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PreSync
  name: mcp-apply-iommu
  namespace: {{ .Values.job.namespace }}
spec:
  template:
    spec:
      containers:
        - image: {{ .Values.job.image }}
          command:
            - /bin/bash
            - -c
            - |
              oc apply -f https://raw.githubusercontent.com/intel/intel-technology-enabling-for-openshift/main/machine_configuration/100-alternative-fw-path-for-worker-nodes.yaml
              oc apply -f https://raw.githubusercontent.com/intel/intel-technology-enabling-for-openshift/main/machine_configuration/100-intel-qat-intel-iommu-on.yaml
          imagePullPolicy: IfNotPresent
          name: mcp-apply-iommu
      restartPolicy: Never
      serviceAccount: {{ .Values.serviceAccountName }}
      serviceAccountName: {{ .Values.serviceAccountName }}