kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: retrievers
  namespace: {{ .Values.global.gaudillm.namespace }}
spec:
  output:
    to:
      kind: "ImageStreamTag"
      name: "gen-ai-comps:retriever-redis-server"
  failedBuildsHistoryLimit: 5
  successfulBuildsHistoryLimit: 5
  nodeSelector: null
  postCommit: {}
  resources: {}
  runPolicy: SerialLatestOnly
  source:
    contextDir: .
    git:
      uri: https://github.com/opea-project/GenAIComps.git
    type: Git
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: comps/retrievers/langchain/docker/Dockerfile
      {{- if .Values.global.gaudillm.build_envs }}
      env:
      {{- range .Values.global.gaudillm.build_envs }}
      - name: {{ .name }}
        value: {{ .value }}
      {{- end }}
      {{- end }}
  triggers:
  - imageChange:
    type: ImageChange
  - type: ConfigChange
