global: 
  pattern: gaudillm

  clusterDomain: lab.com
  clusterName: ocp

  gaudillm:
    namespace: gaudi-llm
    servingRuntime:
      namespace: rag-demo
      name: tgi-70b-1
    build_envs: [] # http_proxy/https_prxy can be set here
    runtime_envs: []
    
    llm_server_for_gaudi:  
      image: gen-ai-comps:llm-tgi-gaudi-server
