---
- name: Creates directories for certs and keys
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ cert_directory_path }}"

# Create a root certificate and private key to sign the certificates for services
# example.com -client_cert_key_path

- name: Create private key for example.com (RSA, 4096 bits)
  community.crypto.openssl_privatekey:
    path: "{{ client_cert_key_path }}.key"

- name: Create simple self-signed certificate
  community.crypto.x509_certificate:
    path: "{{ client_cert_key_path }}.crt"
    privatekey_path: "{{ client_cert_key_path }}.key"
    provider: selfsigned

# httpbin.example.com -server_cert_key_path

- name: Create private key for httpbin.example.com (RSA, 4096 bits)
  community.crypto.openssl_privatekey:
    path: "{{ server_cert_key_path }}.key"

- name: Generate an OpenSSL Certificate Signing Request
  community.crypto.openssl_csr:
    path: "{{ server_cert_key_path }}.csr"
    privatekey_path: "{{ server_cert_key_path }}.key"
    common_name: httpbin.example.com
    organization_name: httpbin organization

- name: Generate a Self Signed OpenSSL certificate
  community.crypto.x509_certificate:
    path: "{{ server_cert_key_path }}.crt"
    csr_path: "{{ server_cert_key_path }}.csr"
    privatekey_path: "{{ server_cert_key_path }}.key"
    ownca_path: "{{ client_cert_key_path }}.crt"
    ownca_privatekey_path: "{{ client_cert_key_path }}.key"
    provider: selfsigned

# helloworld.example.com -app_cert_key_path

- name: Create private key for helloworld.example.com (RSA, 4096 bits)
  community.crypto.openssl_privatekey:
    path: "{{ app_cert_key_path }}.key"

- name: Generate an OpenSSL Certificate Signing Request
  community.crypto.openssl_csr:
    path: "{{ app_cert_key_path }}.csr"
    privatekey_path: "{{ app_cert_key_path }}.key"
    common_name: helloworld.example.com
    organization_name: helloworld organization

- name: Generate a Self Signed OpenSSL certificate
  community.crypto.x509_certificate:
    path: "{{ app_cert_key_path }}.crt"
    csr_path: "{{ app_cert_key_path }}.csr"
    privatekey_path: "{{ app_cert_key_path }}.key"
    ownca_path: "{{ client_cert_key_path }}.crt"
    ownca_privatekey_path: "{{ client_cert_key_path }}.key"
    provider: selfsigned

# client -cli_cert_key_path

- name: Create private key for client.example.com (RSA, 4096 bits)
  community.crypto.openssl_privatekey:
    path: "{{ cli_cert_key_path }}.key"

- name: Generate an OpenSSL Certificate Signing Request
  community.crypto.openssl_csr:
    path: "{{ cli_cert_key_path }}.csr"
    privatekey_path: "{{ cli_cert_key_path }}.key"
    common_name: client.example.com
    organization_name: client organization

- name: Generate a Self Signed OpenSSL certificate
  community.crypto.x509_certificate:
    path: "{{ cli_cert_key_path }}.crt"
    csr_path: "{{ cli_cert_key_path }}.csr"
    privatekey_path: "{{ cli_cert_key_path }}.key"
    ownca_path: "{{ client_cert_key_path }}.crt"
    ownca_privatekey_path: "{{ client_cert_key_path }}.key"
    provider: selfsigned
