global: 
  pattern: gaudillm

  clusterDomain: lab.com
  clusterName: ocp

  gaudillm:
    namespace: gaudi-llm
    build_envs: [] # http_proxy/https_prxy can be set here
    runtime_envs: []
    
    chatqna_ui_server:  
      git_ref: a6b3caf
      image: image-registry.openshift-image-registry.svc:5000/gaudi-llm/gen-ai-comps:chatqna-ui-server
